README.md
setup.cfg
src/telliot_feed_examples/__init__.py
src/telliot_feed_examples/reporters/report_legacy_price.py

Bump rev along with some minor doc and example fixes

Release prep

---

src/telliot_feed_examples/reporters/interval.py
tests/conftest.py

Add error message for profitability-check failures.
Update reporter tests to account for expected errors.

Handle errors

---

src/telliot_feed_examples/cli.py
src/telliot_feed_examples/reporters/interval.py

Add optional percent profit flag to CLI.
Change profit check to use percentage.
Fix rewards & costs conversion to USD.

Profit updates

---

README.md
docs/usage.md
mkdocs.yml

Add usage page for `telliot-examples` CLI.

docs update

---

src/telliot_feed_examples/reporters/interval.py

Closes #48. 
Fixes logging levels, so expected messages are not logged as errors.

Change log levels

---

src/telliot_feed_examples/olympus.py
src/telliot_feed_examples/sources/coingecko.py
tests/test_olympus.py

This PR demonstrates a proof of concept OHM/ETH `SpotPrice` feed using a single data source (coingecko).
Additional data sources are needed for a more robust/decentralized data feed.

OHM-ETH proof of concept

---

src/telliot_feed_examples/__init__.py

Remove development version syntax

Bump version

---

src/telliot_feed_examples/utils/contract.py
src/telliot_feed_examples/utils/oracle_write.py

Ties in with `telliot-core` PR https://github.com/tellor-io/telliot-core/pull/193

Move write_with_retries to contract utilities

---

docs/getting-started.md
docs/usage.md
scripts/abi.py
scripts/submit_polygon_testnet.py
src/telliot_feed_examples/cli.py
src/telliot_feed_examples/reporters/interval.py
src/telliot_feed_examples/reporters/tellorflex.py
src/telliot_feed_examples/sources/ampl_usd_vwap.py
src/telliot_feed_examples/sources/binance.py
src/telliot_feed_examples/sources/bitfinex.py
src/telliot_feed_examples/sources/bitflyer.py
src/telliot_feed_examples/sources/bittrex.py
src/telliot_feed_examples/sources/coinbase.py
src/telliot_feed_examples/sources/coingecko.py
src/telliot_feed_examples/sources/gemini.py
src/telliot_feed_examples/sources/kraken.py
src/telliot_feed_examples/sources/price_aggregator.py
src/telliot_feed_examples/sources/uspce.py
tests/cli/test_cli.py
tests/conftest.py
tests/reporters/test_interval_reporter.py
tests/reporters/test_polygon_reporter.py

Adds basic `PolygonReporter` 
TODO:

Add Polygon TellorFlex Reporter

---

src/telliot_feed_examples/cli.py
src/telliot_feed_examples/reporters/interval.py
src/telliot_feed_examples/reporters/tellorflex.py
tests/conftest.py
tests/reporters/test_interval_reporter.py
tests/reporters/test_polygon_reporter.py
tests/reporters/test_uspce_reporter.py
tests/test_olympus.py

Completed integration with core update here:
- [Replace StakerList config with encrypted keys using ChainedAccounts](https://github.com/tellor-io/telliot-core/pull/203)

Moved from StakerList to ChainedAccounts for account management.

---

docs/getting-started.md
docs/usage.md

Adds usage instructions for reporting on ethereum & polygon

Update usage docs page

---

src/telliot_feed_examples/cli.py
tests/reporters/test_polygon_reporter.py

Selects tellorFlex reporter if chain id is 122

Update for Fuse integration

---

src/telliot_feed_examples/feeds/__init__.py
tests/feeds/test_active_feeds.py

Adds test to make sure there's a feed for every active query tag from the query catalog.

Ensure active feed support

---

src/telliot_feed_examples/sources/diva_protocol.py
src/telliot_feed_examples/utils/diva_protocol.py
tests/sources/test_diva_manual_entry_source.py
tests/utils/test_diva.py

Add manual data entry for DIVA price reference assets

---

src/telliot_feed_examples/sources/price/spot/uniswapV3.py
tests/sources/test_spot_price_sources.py

-increased timeout time
-modified logging output
-added testing for timeout to return None if it fails

fix timeout, add test

---

src/telliot_feed_examples/sources/price/spot/nomics.py
src/telliot_feed_examples/sources/price/spot/uniswapV3.py

Removes deprecated method name warning when running tests.

Remove deprecation warning

---

.gitignore
.pre-commit-config.yaml
scripts/generate_price_history_csv.py
src/telliot_feed_examples/feeds/diva_protocol_feed.py
src/telliot_feed_examples/sources/price/historical/kraken.py
tests/feeds/test_btc_usd_feed.py
tests/feeds/test_diva_feed.py
tests/feeds/test_eth_jpy_feed.py
tests/feeds/test_eth_usd_feed.py
tests/feeds/test_trb_usd_feed.py
tests/reporters/test_interval_reporter.py
tests/sources/test_historical_price_sources.py
tox.ini

- fixes tests failing because pools no longer exist bc diva contract update
- update pool params getter to access params by attribute rather than indexing into tuple

Update DIVA Protocol integration parts to match changes in telliot-core

---

src/telliot_feed_examples/reporters/interval.py

#116
retries to the api request until it gets a response.
file changes in both telliot-feed-examples and telliot-core
no tests added yet. tested manually.

retry ethgasstation api if no response returned

---

src/telliot_feed_examples/reporters/interval.py
tests/reporters/test_interval_reporter.py

Handle no token prices retrieved in profit calculation

---

src/telliot_feed_examples/cli.py
src/telliot_feed_examples/feeds/__init__.py
tests/feeds/test_active_feeds.py

- Example report command: `telliot-examples -a dev-acct-bags report -qt morphware-v1 -gl 4000000 -gp 3`
- Successful report transaction: https://mumbai.polygonscan.com/tx/0x534fe40e4c5e76b28ef7a224e155dab66fd2e6d855c2c536581305def2f82b3f
(chonky gas)

Support reporting response to Morphware query V1

---

src/telliot_feed_examples/reporters/interval.py
tests/conftest.py
tests/reporters/test_interval_reporter.py

Related: #169 
Want to hear back from @Spuddyminer to make sure this err doesn't occur again before closing the issue..

Fix profit calc err when missing token price

---

scripts/get_binance_tickers.py
scripts/get_bitlyer_tickers.py
src/telliot_feed_examples/feeds/trb_usd_feed.py
src/telliot_feed_examples/sources/price/spot/coingecko.py
tests/sources/test_spot_price_sources.py

Log rate limiting from Coingecko price source

---

src/telliot_feed_examples/sources/gas_price_oracle.py
tests/sources/test_gas_price_oracle_source.py

Sets up and tests a data source for the gas price oracle query type. It requests the Owlracle history API

Gas price oracle data source

---

tests/feeds/test_active_feeds.py
tests/feeds/test_gas_price_oracle_feed.py
tests/sources/test_gas_price_oracle_source.py

Skip failing gasprice oracle tests

---

src/telliot_feed_examples/sources/price/spot/gemini.py
tests/feeds/test_btc_usd_feed.py
tests/reporters/test_polygon_reporter.py
tests/sources/test_spot_price_sources.py
tests/test_autopay.py
tests/test_bct_usd.py
tests/test_olympus.py
tests/test_vesq.py

Use local node for more tests

---

tests/conftest.py
tests/reporters/test_interval_reporter.py
tests/reporters/test_polygon_reporter.py
tests/sources/test_ampl_usd_vwap_source.py
tests/sources/test_spot_price_sources.py
tests/test_dai_usd.py

Make the CI & local test runs faster by doing them parallel. 
More info: https://eth-brownie.readthedocs.io/en/stable/tests-pytest-intro.html#using-xdist-for-distributed-testing

Enable distributed testing

---

src/telliot_feed_examples/reporters/interval.py
tests/reporters/test_interval_reporter.py

Handle master contract read connection failure

---

src/telliot_feed_examples/cli.py
src/telliot_feed_examples/reporters/interval.py
src/telliot_feed_examples/reporters/reporter_autopay_utils.py
src/telliot_feed_examples/reporters/tellorflex.py
src/telliot_feed_examples/sources/morphware.py
tests/sources/test_historical_price_sources.py

added --wait-period flag to use in cli when starting reporter that takes an integer (in seconds for a sleep period) so that calls to infura can be slowed if desired.

add wait period between checking for tips

---

contracts/TellorX/TellorXMasterMock.sol
contracts/TellorX/TellorXOracleMock.sol
tests/conftest.py
tests/reporters/test_interval_reporter.py
tests/reporters/test_uspce_reporter.py
tests/test_autopay.py
tests/utils/test_oracle_write.py

test_oracle_write.py
test_interval_reporter.py
test_uspce_reporter.py

switching tests to use brownie

---

contracts/integrations/DIVAProtocolMock.sol
src/telliot_feed_examples/feeds/diva_protocol_feed.py
tests/feeds/test_diva_feed.py

Use local node for DIVA feed tests

---

docs/usage.md

Include withdraw stake instructions

---

src/telliot_feed_examples/sources/gas_price_oracle.py
tests/feeds/test_gas_price_oracle_feed.py

caught the relevant exception + caught it in the tests

gas price oracle: catch exceeded api limit

---

src/telliot_feed_examples/cli.py
src/telliot_feed_examples/reporters/reporter_autopay_utils.py

Simple changes to add networks Optimism Kovan, Harmony Mainnet, and Harmony Testnet

Added networks 69, 1666600000, & 1666700000

---

src/telliot_feed_examples/sources/price/spot/kraken.py

Fix Kraken spot price service bug

---

src/telliot_feed_examples/reporters/rng_interval.py
src/telliot_feed_examples/reporters/tellorflex.py

Closes [#301](https://github.com/tellor-io/telliot-core/issues/301)

Handle unsuccessful contract calls in tip listener & RNG reporter

---

src/telliot_feed_examples/cli.py
src/telliot_feed_examples/reporters/reporter_autopay_utils.py

New network added: Arbitrum Rinkeby, but I wasn't able to report on this network. Still trying to find the bug, but I will make an issue also in telliot-core after these changes are merged.

added arbitrum

---

README.md
docs/usage.md
setup.cfg
src/telliot_feed_examples/utils/reporter_utils.py
tests/utils/test_reporter_utils.py

Use reporter & feeds CLI tool w/ command `telliot-feeds` instead of `telliot-examples`.

Update CLI entrypoint name

---

src/telliot_feeds/sources/price/spot/coingecko.py

coingecko reporter error

---

src/telliot_feeds/cli/commands/report.py
src/telliot_feeds/feeds/__init__.py

Related: [#61](https://github.com/tellor-io/dataSpecs/issues/61)

Map datafeed to eur-usd-spot query tag

---

src/telliot_feeds/reporters/reporter_autopay_utils.py

catch keyerror for query id not in catalog

---

requirements-dev.txt
setup.cfg

little fix to force version 0.5.1

forces multicall version 0.5.1

---

src/telliot_feeds/cli/utils.py
src/telliot_feeds/queries/gas_price_oracle.py

small change to handle an index error, when typing isn't set to optional.

fix typing error

---

src/telliot_feeds/feeds/spot_price_manual_feed.py

add manual spot price feed

---

src/telliot_feeds/cli/commands/query.py
src/telliot_feeds/cli/main.py
src/telliot_feeds/queries/abi_query.py
src/telliot_feeds/queries/query.py
tests/cli/test_query_cmd.py
tests/queries/test_query_support.py

Decode query data & submitted values using CLI

---

docs/usage.md

--build-feed docs first pass

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/legacy_request_manual_feed.py

txn using --build-feed flag:  https://rinkeby.etherscan.io/tx/0x01af8785948d278113b04f562779299d0b5ae97004f5090b900c29d4e8171f06

add legacy manual-feed

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/numeric_api_response_manual_feed.py
src/telliot_feeds/sources/manual_sources/numeric_api_manual_response.py
src/telliot_feeds/sources/numeric_api_response.py

txn using --build-feed flag (telliot-feeds -a  my-mumbai-acct report --build-feed -p YOLO) and choosing ```NumericApiManualResponse```: https://mumbai.polygonscan.com/tx/0x7caa911f70943bd4e8e03e3de7817d4880f7d08424ef51f8dbcfb0f0eede2b99

numeric api manual source

---

src/telliot_feeds/sources/price/historical/poloniex.py
tests/sources/test_historical_price_sources.py

Fix historical price source test bugs

---

src/telliot_feeds/reporters/tellorflex.py

reporter should get a new datafeed or Attempt to get a new datafeed every time it loops.  Only happens with tellorflex reporter.

attempt to fix reporter looping same datafeed

---

src/telliot_feeds/integrations/diva_protocol/README.md

Add important instruction to DIVA Protocol integration README

---

src/telliot_feeds/feeds/ric_usd_feed.py

remove bad source for ric/usd

---

src/telliot_feeds/queries/query_catalog.py

add RNG example to catalog

---

src/telliot_feeds/__init__.py

Bump the package version. Another release will be made to include @tallywiesenberg 's bug fix
Submitted value using this cmd that previously errored out bc of the bittrex json decode error:
`telliot-feeds -a dev-acct-bags report -p YOLO -qt matic-usd-spot --submit-once`

Update version to fix small bug

---

src/telliot_feeds/__init__.py

New version is `0.1.2dev0`.
Following the release process: [here](https://tellor-io.github.io/telliot-core/contributing/#new-release-processchecklist)
- Please make sure docs updates are both thorough and easy …

Change version to development

---

src/telliot_feeds/cli/commands/report.py
src/telliot_feeds/reporters/reporter_autopay_utils.py

Summary: Allows for reporting on the new Arbitrum tellorFlex contracts.
After merging, will do a fresh install of Telliot to verify that reporting on arbitrum works with these changes. 
This pull request Closes Issue #335

network IDs added for Arbitrum One

---

src/telliot_feeds/feeds/btc_usd_feed.py

a little fix for a mistake with the Kraken asset label.

Fix for Kraken (xbt to btc)

---

src/telliot_feeds/feeds/btc_usd_feed.py
src/telliot_feeds/sources/price/spot/kraken.py
tests/sources/test_spot_price_sources.py

fixed the previously broken btc/xbt kraken feed fix

add xbt to kraken assets

---

requirements-dev.txt

- Closes #344
- Github actions built docs successfully: https://github.com/tellor-io/telliot-feeds/actions/runs/3009306953
- Docs build locally:
```console
(env) ➜  telliot-feeds git:(main) ✗ mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /Users/owen/tellor/telliot-feeds/site
INFO     -  Documentation built in 0.60 seconds
(env) ➜  telliot-feeds git:(main) ✗ mkdocs gh-deploy
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /Users/owen/tellor/telliot-feeds/site
INFO     -  Documentation built in 0.57 seconds
WARNING  -  Version check skipped: No version specified in previous deployment.
INFO     -  Copying '/Users/owen/tellor/telliot-feeds/site' to 'gh-pages' branch and pushing to GitHub.
Enumerating …
```

Fix docs build error

---

src/telliot_feeds/sources/price/historical/kraken.py
src/telliot_feeds/sources/price/historical/kraken_ohlc.py
src/telliot_feeds/sources/price/spot/kraken.py
tests/sources/test_historical_price_sources.py

Kraken DataSource (for current price and historical price) still raised an exception when an asset isn't supported. I replaced it with logging to not interrupt other programs (i.e. disputable-values-monitor)
Tests continue to pass, will test in disputable values monitor as well to close https://github.com/tellor-io/disputable-values-monitor/issues/37
- Please reference the related issue by including "Closes `<link …

remove raised exception in kraken data source

---

src/telliot_feeds/cli/utils.py
src/telliot_feeds/feeds/__init__.py
tests/cli/test_cli.py

- Closes #308 
- Example console output:
```console
Choose query type:
1 -- DailyVolatility
2 -- DivaProtocol
3 -- GasPriceOracle
4 -- LegacyRequest
5 -- NumericApiManualResponse
6 -- NumericApiResponse
7 -- SnapshotOracle
8 -- SpotPrice
9 -- StringQuery
10 -- TWAP
11 -- TellorRNG
```
- ran and tried to break it locally
- updated the relevant CLI tests
- Please reference the related issue by including "Closes …

Improve build feed UI

---

src/telliot_feeds/reporters/reporter_autopay_utils.py
tests/reporters/test_autopay_multicalls.py

- error handle a none return from multicall response.
- remove a function and simplify code to avoid confusion.
Closes #381 #380 
- added test that passes locally for the error handle
- ran two tests related to this file and they both pass
- If no issue exists, please create a feature enhancement …

Fix error 381

---

src/telliot_feeds/sources/price/spot/gemini.py
tests/sources/test_spot_price_sources.py

- Closes #392 
- the `.strerror` attribute was None, so an error was thrown when it tried to iterate over it. I cast the whole dict as a string to guarantee that it's an iterable. Also, checked for None returned
- added a test
- …

Fix Gemini spot price source bug

---

src/telliot_feeds/sources/price/spot/coinmarketcap.py
tests/sources/test_spot_price_sources.py

Catches responses with invalid status codes to prevent empty 'data' variable that is indexed by strings after the try-catch clause.
Added to preexisting CMC test `test_coinmarketcap` a mocked scenario of a 404 returned in the `Response`
- If no issue exists, please create a feature enhancement …

catch-empty-data

---

src/telliot_feeds/cli/commands/query.py
src/telliot_feeds/cli/utils.py
tests/cli/test_query_cmd.py
tests/cli/test_utils.py

- Closes #353 
Added two tests:
- `tests/cli/test_query_cmd.py::test_new_query`
- `tests/cli/test_utils.py::test_build_query`
- Please make sure docs updates are both thorough and easy to reproduce by somebody …

Add new query command

---

src/telliot_feeds/__init__.py

Remove dev0 from version name for release

---

src/telliot_feeds/reporters/tellor_360.py
tests/reporters/test_360reporter.py

Fixes unbound variable in TBR calculation
tests success of the function that creates and calls it. 
`tests/reporters/test_360reporter.py::test_360_reporter_rewards`
- Please make sure docs updates are both …

Bug fix: `time_based_rewards` referenced before assignment

---

src/telliot_feeds/cli/commands/report.py
tests/cli/test_cli.py

- Closes #424 
- See `tests/cli/test_cli.py::test_stake_flag`
- Example console output:
```console
$ telliot-feeds report --help
...
-dma, --diva-middleware-address TEXT
DIVA Protocol middleware contract address
-custom, --custom-contract TEXT
Use a custom contract to report to oracle
-s, --stake FLOAT               ❗Telliot will automatically stake more TRB
if your stake is below or falls below the
stake amount required to report. If you
would like to stake more than required,
enter the TOTAL stake amount you wish to be
staked. For example, if you wish to stake
1000 TRB, enter 1000.
--flex-360 / --old-flex         Choose between tellor360 reporter or old
flex
...
```
- Please reference the related issue by including "Closes `<link to …

Make staking prompt into optional flag

---

src/telliot_feeds/integrations/diva_protocol/utils.py
src/telliot_feeds/reporters/tellor_360.py
src/telliot_feeds/reporters/tellorflex.py

- Added fetch_gas_price method to tellor_360_reporter to query separate gas station api instead of query matic gas station for all chain ids.
- Fetches gas price from eth-gas-station for Mainnet and Görli and matic-gas-station for the rest of the chains.
- Needs to take into account other chain ids like arbitrum and optimism.
- Couldn't figure out how to test in the code so just reported to mumbai and goerli to see if gas price was different and that was the case.
- Paid 53 gwei per gas in Görli txn [Link](https://goerli.etherscan.io/tx/0xdb043e0004df5f7a0ef7663b61ff56264bcd830b5d5fab8ec1f21f450d3cae1f)
- Paid 563 gwei per gas in Mumbai [Link](https://mumbai.polygonscan.com/tx/0xd30ada3f0843dbf7d1edda9ff63c69bbfe7637a8933ed1b0442c815a67f404a6)
- No tests or issue …

Customize fetch_gas_price method for tellor_360

---

src/telliot_feeds/integrations/diva_protocol/sources.py
tests/integrations/diva_protocol/test_e2e_create_report_settle_pool.py
tests/sources/test_historical_price_sources.py

- Closes #437 
- Poloniex historical price was consistently off
- Confirmed that 2 sources are now being used when tests run:
```console
INFO     telliot_feeds.sources.price_aggregator:price_aggregator.py:91 Running median on [1183.61, 1194.52]
INFO     telliot_feeds.sources.price_aggregator:price_aggregator.py:96 Feed Price: 1189.065 reported at time 2022-11-15 02:52:13.324523+00:00
INFO     telliot_feeds.sources.price_aggregator:price_aggregator.py:97 Number of Sources used for this report are: 2
```
- Please include tests. Fixes without tests will not be accepted …

Remove Poloniex from DIVA Protocol BTC/USD data source

---

src/telliot_feeds/utils/reporter_utils.py
tests/utils/test_reporter_utils.py

- Related #436
- Adds `has_native_token_funds`, which can be introduced throughout the codebase (in reporters probably) in another PR
- Tested in `tests/utils/test_reporter_utils.py::test_has_native_token_funds` …

Check if account has native token funds

---

src/telliot_feeds/integrations/diva_protocol/report.py
src/telliot_feeds/reporters/interval.py
src/telliot_feeds/reporters/rng_interval.py
src/telliot_feeds/reporters/tellorflex.py
src/telliot_feeds/utils/cfg.py
src/telliot_feeds/utils/reporter_utils.py
tests/reporters/test_360reporter.py
tests/utils/test_reporter_utils.py

- Closes #436 
- Adds a check using `has_native_token_funds()` to the base reporter and DIVA reporter
- Added `tests/reporters/test_tellor360.py::test_no_native_token` to simulate the expected behavior
- Please …

Use check for available native tokens in reporters

---

src/telliot_feeds/cli/commands/report.py
src/telliot_feeds/cli/utils.py
src/telliot_feeds/sources/price/historical/kraken.py
tests/sources/test_historical_price_sources.py

- from DIVA's fix [here](https://github.com/divaprotocol/diva-monorepo/pull/671):
```
The Kraken API only returns the latest 1000 prices. This means if we fetch prices starting from the timestamp max_time_away it can be that the expiryTime is not in the data. Example: If there are prices every second and max_time_away= 60 min then we have 3600 prices between max_time_away and expiryTime and only fetch the first 1000.
-> We solve this by fetching all prices starting from expiryTime - 1 min . If this is empty we fetch prices starting from expiryTime - 2 min, and so on until expiryTime - max_time_away.
```
- relevant tests pass: `tests/sources/test_historical_price_sources.py::test_kraken_get_price`
- Please reference the related issue by …

Implement DIVA Protocol Kraken historical price source fix

---

tests/reporters/test_flex_reporter.py

- The Tellor Flex reporter test names were specific to Polygon, now they are called tellor_flex
- ran the changed tests, they pass
- Please make sure docs updates are both thorough and easy to reproduce by …

Rename Tellor Flex reporter tests

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/albt_usd_feed.py
src/telliot_feeds/queries/price/spot_price.py
src/telliot_feeds/queries/query_catalog.py
src/telliot_feeds/sources/price/spot/binance.py
src/telliot_feeds/sources/price/spot/coingecko.py
src/telliot_feeds/sources/price/spot/coinmarketcap.py
src/telliot_feeds/sources/price/spot/nomics.py

Add ALBT/USD median feed

---

setup.cfg
src/telliot_feeds/cli/commands/config.py
src/telliot_feeds/cli/main.py
tests/cli/test_cli.py
tox.ini

- Changes CLI entry name from `telliot-feeds` to `telliot`
- Adds the `config` command
- Closes #330  
- Added tests for new cmd from `telliot-core`
- Tested locally
- Please make sure docs updates are both …

Change cli entry name & add config cmd

---

src/telliot_feeds/sources/price_aggregator.py

Fix type error in price aggregator

---

src/telliot_feeds/sources/price/spot/bitfinex.py
src/telliot_feeds/sources/price/spot/coinmarketcap.py
tests/sources/test_spot_price_sources.py

- Adds tests for bitfinex price source
- Adds tests
**Happy …

Fix type bug

---

tests/reporters/test_360_reporter.py

- Closes #460 
- Added a test that mocks the get_feed_and_tip function so it returns a feed that has a manual input source. The test makes sure the reporter lock check works 
- Please make sure docs updates are …

Add test ensure checks reporter lock even if manual source

---

src/telliot_feeds/reporters/interval.py
src/telliot_feeds/reporters/tellor_flex.py
tests/reporters/test_360_reporter.py
tests/reporters/test_interval_reporter.py

- Closes #444 
- relevant test passes: `tests/reporters/test_interval_reporter.py::test_get_num_reports_by_id`
- Please make sure docs updates are both thorough and easy to reproduce by somebody with limited …

Remove old function use

---

src/telliot_feeds/cli/commands/report.py
src/telliot_feeds/reporters/tellor_360.py
src/telliot_feeds/reporters/tellor_flex.py
src/telliot_feeds/utils/reporter_utils.py
tests/cli/test_cli.py
tests/conftest.py
tests/reporters/test_360_reporter.py
tests/reporters/test_flex_reporter.py
tests/utils/test_reporter_utils.py

- Closes #480 
- Adds command `--random-feeds/--no-random-feeds` to report using a random datafeed from the catalog
- Adds command `--check-rewards/--no-check-rewards` to skip both profit & tips checking. tips will be checked if the user doesn't specify query tag or use the random feeds flag
- Fixes some reporter tests
- [successful report tx](https://mumbai.polygonscan.com/tx/0xb3d2020374d6a78a530232c67172299e02e981755e759d7816f20cd511f65a8a) using new commands `telliot -a myacct report -mnb 0 -rf -ncr`
- Please include tests. Fixes without tests will not be accepted …

Enable random feed reporting & profit/tips/rewards check skip

---

setup.cfg

- Closes #489 
- [successful report tx](https://mumbai.polygonscan.com//tx/0x7c597d3ca0587566a659ac02f6fb769b4c7a401b2ff1dd12de1164c8027eb61f) using cmd `telliot -a dev-acct-bags report -mnb 0 -rf -ncr`
- Please …

Lock dependency versions

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/rai_usd_feed.py
src/telliot_feeds/queries/price/spot_price.py
src/telliot_feeds/queries/query_catalog.py
src/telliot_feeds/sources/price/spot/coingecko.py
src/telliot_feeds/sources/price/spot/kraken.py
src/telliot_feeds/sources/price/spot/nomics.py

- Closes #491 
- submitted value on mumbai [here](https://mumbai.polygonscan.com/tx/0xbdb112e1bad6391fee15758df9136f028e02cfe96646699f6569de0af24df16f)
- Please make sure docs updates are both thorough and easy …

Add RAI/USD datafeed

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/twap_manual_feed.py

- Closes #488 
- successful submitted value tx [here](https://mumbai.polygonscan.com//tx/0x004876e64d3c37eedec0dbafb6be756de9e69bae9dae5e8054b83aa5a7fbcaf8). reproduce w/ command `telliot -a myacct report -qt twap-eth-usd-example -ncr`
- If no issue exists, please create a feature enhancement issue …

Fix TWAP manual feed encoding error

---

docs/documentation.md
docs/getting-started.md
docs/index.md
docs/usage.md

Remove tellorx-specific stuff, simplify install instructions

---

docs/getting-started.md
docs/usage.md

- Made env / docker setup more clear. Removed old use of `telliot-feeds` cli entrypoint
- Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature …

Update setup & usage to reflect latest cmds

---

setup.cfg
src/telliot_feeds/reporters/reporter_autopay_utils.py
src/telliot_feeds/reporters/tips/__init__.py

Update multicall to 0.7.0
add Chaido testnet multicall address
- …

Update multicall version, add chiado support

---

docs/getting-started.md
setup.cfg
src/telliot_feeds/reporters/reporter_autopay_utils.py
src/telliot_feeds/reporters/tips/__init__.py

I read through and changed the getting started page with a goal of making it flow a little bit better for people who are unfamiliar with tellor / telliot.
This was a great exercise for me, because I'm now familiar with how to edit these docs pages. I've got a lot of experience running telliot so I feel like I can do a lot of good here. Thanks!

telliot docs - proposed changes to getting started 

---

Dockerfile
docker-compose.yml
docs/new-release.md
mkdocs.yml

- Closes #526 
- built & served docs locally, checked all links …

Correct docker release instructions

---

src/telliot_feeds/integrations/diva_protocol/report.py
src/telliot_feeds/reporters/custom_reporter.py
src/telliot_feeds/reporters/flashbot.py
src/telliot_feeds/reporters/interval.py
tests/reporters/test_360_reporter.py

- Closes #531 
- added test: `tests/reporters/test_360_reporter.py::test_fail_get_account_nonce`
- successful report tx [here](https://mumbai.polygonscan.com//tx/0xaee2cc6e1f52aee9112cc034594bfa520c3aadae5f9882b1d88bfcca41c311dc)
- …

Add err handling for getting account nonce

---

docs/add-chain.md
docs/add-spot-price.md

- There's a couple missing steps in the docs about adding a new chain. For profit checks, we need the chain's native token spot price in USD. So a feed needs to be created for this if it doesn't exist.
- Closes #535 
- built & reviewed docs locally
- If no issue exists, please create a feature …

Include steps for native token price of new chain

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/xdai_usd_feed.py
src/telliot_feeds/queries/price/spot_price.py
src/telliot_feeds/queries/query_catalog.py
src/telliot_feeds/reporters/reporter_autopay_utils.py
src/telliot_feeds/sources/price/spot/coingecko.py
src/telliot_feeds/utils/reporter_utils.py

Proposing these changes to allow for reporting on Gnosis Chain mainnet. I also added an xdai feed that is seperate from the DAI feed. I will continue to look into the sources and make another pull request when I find more sources, or determine that we can just use the DAI price.

Added Gnosis chain and xdai feed

---

docs/add-spot-price.md

Change example to eth/usd, add more info on sources chosen

---

src/telliot_feeds/cli/main.py
tests/cli/test_cli.py
tests/conftest.py

- Closes [#344](https://github.com/tellor-io/telliot-core/issues/344)
- Added test: `tests/cli/test_cli.py::test_no_accounts_msg`
- Please make sure docs updates are both thorough and easy to reproduce by …

Tell user they need to add account instead of throwing err

---

docs/getting-started.md

Add test trb & native token to prereqs

---

docs/getting-started.md
docs/usage.md

- Closes #554 
- Closes #549 
- Closes #547 
- built successfully, viewed locally
- Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature that …

Update docs based on workgroup feedback #2

---

src/telliot_feeds/cli/utils.py

- Closes #550 
- Tried. New output example:
```console
...
Priority fee (gwei): None
Gas price speed: fast
Desired stake amount: 10.0
Minimum native token balance (e.g. ETH if on Ethereum mainnet): 0.25
Press [ENTER] to confirm settings.
```
- If no issue exists, please create a feature enhancement …

Edit confirm reporter settings msg

---

README.md
docs/getting-started.md
docs/usage.md
src/telliot_feeds/cli/commands/report.py
src/telliot_feeds/cli/commands/settle.py
src/telliot_feeds/cli/main.py
src/telliot_feeds/cli/utils.py
tests/cli/test_cli.py

- Closes #546 
- Example report tx using updated command: `telliot report -a acct -ncr -rf`: https://mumbai.polygonscan.com//tx/0xe7a0b2f7f7285cd96f1860d7375209b803e3ff441780ceb6ecb04651fb875300
- Please make …

Move signature account to report cmd

---

docs/getting-started.md
src/telliot_feeds/sources/blockhash_aggregator.py
src/telliot_feeds/utils/cfg.py
tests/conftest.py
tests/sources/test_tellor_rng_source.py

- Closes #543 
- Added tests  & cmd that produced the error no longer does (`telliot config show`) if you delete mainnet config
- Please make sure docs updates are both thorough and easy to reproduce by somebody …

Handle no mainnet config 

---

docs/add-chain.md
docs/add-spot-price.md
docs/contributing.md
tests/feeds/test_eth_usd_feed.py

- Closes #562 
- Closes #565 
- Closes #563 
- Closes #561 
- built & checked docs changes locally
- Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of …

Docs updates from workgroup 2

---

tests/tips/test_feed_suggestion.py
tests/tips/test_selected_queryid.py
tests/tips/test_tips_available_after_submission.py

- Fixed tests in tests/tips folder that were failing.
- Closes #468
- Ran tests locally and they pass
- Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of …

Fix tips/ tests

---

docs/getting-started.md

Small docs update

---

src/telliot_feeds/sources/price/spot/bittrex.py
tests/sources/test_spot_price_sources.py

- Closes #572 
- Added tests to `tests/sources/test_spot_price_sources.py::test_bittrex
- Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature …

Fix no strerr attribute in BittrexSpotPriceSource

---

Dockerfile
docs/getting-started.md
docs/new-release.md

Update docker instructions

---

docs/getting-started.md

Update configs docs

---

docs/getting-started.md

Update docs from feedback for workgroup #3

---

src/telliot_feeds/utils/cfg.py
tests/utils/test_config_utils.py

Only ask for block explorer & rpc urls

---

src/telliot_feeds/feeds/ampl_usd_vwap_feed.py
src/telliot_feeds/sources/ampleforth/ampl_usd_vwap.py
src/telliot_feeds/sources/ampleforth/bitfinex.py
src/telliot_feeds/sources/ampleforth/symbols.py
tests/sources/test_ampl_usd_vwap_source.py

- Removes use of decommissioned AnyBlock source
- Uses a free Bitfinex source instead ported from [here](https://github.com/tellor-io/ampleforth-vwap-api)
- Added test for new source
- Sample reported value [here](https://goerli.etherscan.io/tx/0xc29449cac344c0b35e0cd7c5e644993c0c9e901a1250e65c1c844314086e8333)
- Sample cli output using cmd `telliot report -a dev-acct-1-goerli -qt ampleforth-custom -ncr`
```console
...
INFO    | telliot_feeds.reporters.interval | Current query: {"type":"AmpleforthCustomSpotPrice"}
Bitfinex trades for tAMPUSD: 362
Bitfinex trades for AMPL_UST: 0
Could not get Bitfinex trades for AMPL_UST
Bitfinex trades for UST_USD: 0
Could not get Bitfinex trades for UST_USD
Bitfinex trades for AMPL_BTC: 0
Could not get Bitfinex trades for AMPL_BTC
Bitfinex trades for …
```

Remove anyblock source, add bitfinex source for AMPL/USD VWAP

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/aave_usd_feed.py
src/telliot_feeds/feeds/avax_usd_feed.py
src/telliot_feeds/feeds/badger_usd_feed.py
src/telliot_feeds/feeds/bch_usd_feed.py
src/telliot_feeds/feeds/comp_usd_feed.py
src/telliot_feeds/feeds/crv_usd_feed.py
src/telliot_feeds/feeds/doge_usd_feed.py
src/telliot_feeds/feeds/dot_usd_feed.py
src/telliot_feeds/feeds/eul_usd_feed.py
src/telliot_feeds/feeds/fil_usd_feed.py
src/telliot_feeds/feeds/gno_usd_feed.py
src/telliot_feeds/feeds/link_usd_feed.py
src/telliot_feeds/feeds/ltc_usd_feed.py
src/telliot_feeds/feeds/shib_usd_feed.py
src/telliot_feeds/feeds/uni_usd_feed.py
src/telliot_feeds/feeds/usdt_usd_feed.py
src/telliot_feeds/feeds/yfi_usd_feed.py
src/telliot_feeds/queries/price/spot_price.py
src/telliot_feeds/queries/query_catalog.py
src/telliot_feeds/sources/price/spot/coingecko.py
tests/feeds/test_pop_spot_price_feeds.py

Added feeds with at least 3 sources for the following spot price pairs:
AAVE/USD
AVAX/USD 
BADGER/USD 
BCH/USD 
COMP/USD 
CRV/USD 
DOGE/USD  
DOT/USD 
EUL/USD 
FIL/USD 
GNO/USD
LINK/USD 
LTC/USD 
SHIB/USD 
UNI/USD
USDT/USD 
YFI/USD
I did not add any local tests, but instead submitted each one to our testnet contracts on goerli/mumbai to check that all sources are working properly and giving good values. I can provide a link to a transaction for each one if needed.
- Please include tests. Fixes without tests will not be accepted unless it's related to the documentation …

added LOTS of popular feeds

---

Dockerfile

bump version in Dockerfile

---

src/telliot_feeds/reporters/custom_reporter.py
src/telliot_feeds/reporters/interval.py
src/telliot_feeds/reporters/tellor_flex.py

- Closes #606 
- submitVal tx [here](https://mumbai.polygonscan.com//tx/0x797713e9ce569e86df9e72c038904f074a77c72418c33cc27a11625d2b2f5aaa) using the command `telliot report -a myacct -ncr -rf`
- Please make …

Fix gas fetch err

---

src/telliot_feeds/sources/ampleforth/ampl_usd_vwap.py
src/telliot_feeds/sources/ampleforth/bitfinex.py
src/telliot_feeds/sources/ampleforth/symbols.py

Closes #597 
Fix bitfinex api. Wasn't fetching trades for tAMPUST, tUSTUSD, tAMPBTC, tBTCUSD  data for vwap calculations.
Checked these tests and they are passing:
- test_spot_price_sources.py 
- test_ampl_usd_vwap_source.py
- Please …

Fix bitfinex api source

---

src/telliot_feeds/cli/commands/report.py
src/telliot_feeds/reporters/interval.py
src/telliot_feeds/reporters/tellor_flex.py
src/telliot_feeds/utils/reporter_utils.py

Add max priority fee range flag to allow priority fee increase from cli.
Max priority fee range was capped at 1.5, increased to 80 gwei and can now be changed through cli
Closes #623 
[Chiado txn](https://blockscout.com/gnosis/chiado/tx/0xc65dd55f532a55b11db2b34470a4d10c34b0488808142f1812ebcb05e2e1bdc7)
[Mumbai txn](https://mumbai.polygonscan.com//tx/0xa91615cfe126097656c7e97ff2ff5966c816b335b20d1d6de4c05611a6f5360d)
[Arbitrum-goerli](https://goerli.arbiscan.io//tx/0x190917fef673e22a4a28e5f0fa6d961254e2cd0195c3bc92b567b9dfb82313f3)
- Please include tests. Fixes without …

Add max priority fee range flag

---

src/telliot_feeds/reporters/flashbot.py
tests/reporters/test_flashbot_reporter.py

Closes #615 
Add try except on bundle and except HTTPError.
Add test that imitates http error behavior when making request to send bundle.
- Please make sure docs updates are both thorough and easy to reproduce …

Flashbot reporter http error fix

---

src/telliot_feeds/reporters/tips/__init__.py
tests/queries/test_query_catalog.py
tests/reporters/test_360_reporter.py
tests/reporters/test_custom_360_reporter.py
tests/reporters/test_evm_call.py
tests/reporters/test_flashbot_reporter.py
tests/reporters/test_flex_reporter.py
tests/reporters/test_interval_reporter.py
tests/reporters/test_rng_reporter.py
tests/sources/test_spot_price_sources.py
tests/sources/test_tami_calcuation.py
tests/tips/conftest.py
tests/tips/test_feed_suggestion.py
tests/tips/test_selected_queryid.py

Amend tests that were broken from code changes
Run tests to confirm they pass.
- Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you …

Fix failing tests

---

setup.cfg

Add python-dateutil

---

src/telliot_feeds/cli/utils.py
src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/mimicry/macro_market_mashup_feed.py
src/telliot_feeds/reporters/interval.py
src/telliot_feeds/reporters/reporter_autopay_utils.py
src/telliot_feeds/reporters/tellor_flex.py
src/telliot_feeds/reporters/tips/listener/funded_feeds_filter.py
src/telliot_feeds/reporters/tips/listener/tip_listener_filter.py
src/telliot_feeds/utils/reporter_utils.py
tests/cli/test_cli.py
tests/queries/test_query_mimicry_mashup.py
tests/sources/test_evm_call_source.py
tests/tips/test_feed_suggestion.py

Closes #648
Added fix to tip listener that was failing when it couldnt fetch prices from API to calculate price threshold
Added helper function to convert data better when args passed thru cli via build-feed flag
Added typing to CATALOG_FEEDS var which caused other typing errors so fixed those
- Added test for tip listener
- Ran all the tests and all passing for me except for two.  Both cause API is down, but that might be cause I'm getting rate limited. `tests/feeds/test_gas_price_oracle_feed.py::test_fetch_new_datapoint`, `tests/sources/test_spot_price_sources.py::test_pulsechain_subgraph`
- If no issue exists, please …

Fix bugs and tests

---

src/telliot_feeds/cli/commands/settle.py
src/telliot_feeds/cli/utils.py
tests/cli/test_cli.py
tests/cli/test_utils.py

Fixed settle cmd and its test
Remove hardcoded legacy gas price
Added HexBytes wrapper to raise error when int or bool types
Added test for the added wrapper,
Ran all the tests to make sure everything is passing …

Fix diva settle cmd

---

src/telliot_feeds/reporters/tips/__init__.py

Use verified contract address

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/diva_usd_feed.py
src/telliot_feeds/queries/price/spot_price.py
src/telliot_feeds/queries/query_catalog.py
src/telliot_feeds/sources/price/spot/coingecko.py
tests/feeds/test_diva_usd_feed.py

This PR adds a DIVA/USD spot price feed based on coingecko price. 
test report on mumbai: https://mumbai.polygonscan.com/tx/0xf5fa04a8e552449e27887d4a139c92b7b0ef73232c19e556a989df7eed49be09
- closes issue #706

added diva/usd feed (coingecko)

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/pyth_usd_feed.py
src/telliot_feeds/queries/price/spot_price.py
src/telliot_feeds/queries/query_catalog.py
src/telliot_feeds/sources/price/spot/coingecko.py

Adding spot price feed for PYTH/USD spot price.
reported on testnet / verified sources working

add pyth-usd-spot

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/ogv_eth_feed.py
src/telliot_feeds/queries/price/spot_price.py
src/telliot_feeds/queries/query_catalog.py
src/telliot_feeds/sources/price/spot/coingecko.py
src/telliot_feeds/sources/price/spot/uniswapV3.py
tests/feeds/test_ogv_eth_feed.py

This pull request adds OGV/ETH spot price pair for automatic reporting and full telliot functionality.
local tests and reported on sepolia (2 sources only for now)
Closes dataspecs issue that requested OGV/ETH Spot.

OGV/ETH Spot

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/eth_usd_feed.py
src/telliot_feeds/feeds/meth_usd_feed.py
src/telliot_feeds/queries/price/spot_price.py
src/telliot_feeds/queries/query_catalog.py
src/telliot_feeds/sources/price/spot/agni.py
src/telliot_feeds/sources/price/spot/coingecko.py
src/telliot_feeds/sources/price/spot/fusionX.py
src/telliot_feeds/sources/price/spot/maverickV2.py
tests/feeds/test_meth_usd_feed.py

Adds sources and 
all local tests passing, sources working, and test submission on Sepolia https://sepolia.etherscan.io/tx/0x7ecd31582efb726c54ec2442015b92a470aca97f6474c0ff3a13022f2e0d72cb

mETH USD Spot price feed

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/primeeth_eth_feed.py
src/telliot_feeds/queries/price/spot_price.py
src/telliot_feeds/queries/query_catalog.py
src/telliot_feeds/sources/price/spot/coingecko.py
src/telliot_feeds/sources/price/spot/uniswapV3Pool.py
tests/feeds/test_primeeth_eth_feed.py

feed and sources for primeETH/ETH spot
local tests passing and reported on sepolia: https://sepolia.etherscan.io/tx/0x91b986db2a4fec5cc176066f4ada03c6448f1599378297e78dc0a1aa94b77c69

primeETH-ETH-Spot

---

src/telliot_feeds/reporters/customized/conditional_reporter.py

Set query tag to true for conditional reporter (-qt is required)

---

src/telliot_feeds/sources/price/spot/coingecko.py
src/telliot_feeds/utils/cfg.py

Changed the Coingecko Spot Price source to check for an api key and then make the request to the proper api url including the api key as a header if one is provided

Add api key for Coingecko

---

src/telliot_feeds/constants.py
src/telliot_feeds/reporters/tips/__init__.py

Adds BOB mainnet as option for reporting.

Configured for BOB Mainnet

---

src/telliot_feeds/queries/query_catalog.py

adds FileCID to the query example to the query catalog.

add FileCID to QC

---

examples/fileCID_query_example.py
setup.cfg
src/telliot_feeds/feeds/fileCID_manual_feed.py
src/telliot_feeds/feeds/manual_feed.py
src/telliot_feeds/queries/fileCID.py
src/telliot_feeds/queries/query_catalog.py

fix for proper encoding of CID values.
Tested locally in `examples/fileCID_query_example.py` then Submitted on Amoy to be sure:
https://amoy.polygonscan.com//tx/0x466c995328afe56b265763d19dcae7c5629bd3dabb1a688bdbbc487d79ec43ea

Fix CID encoding

---

src/telliot_feeds/cli/commands/conditional.py
src/telliot_feeds/sources/gyd_source.py

Adds a IndexError catch for better stability of the gyd feed. Also fixed the `--unsafe` flag to work when conditional command is used.

Add catch for IndexError on gyd source

---

src/telliot_feeds/sources/gyd_source.py

error catch
- catches UnboundLocalError from balancer subgraph api

catch balancer UnboundLocalError

---

.github/workflows/release.yml

kabob case the repository-url in for github action

Fix setup python

---

src/telliot_feeds/constants.py
src/telliot_feeds/reporters/tips/__init__.py

adds configuration for reporting on Lisk mainnet.

configs for lisk

---

src/telliot_feeds/feeds/__init__.py
src/telliot_feeds/feeds/cult_usd_feed.py
src/telliot_feeds/queries/price/spot_price.py
src/telliot_feeds/queries/query_catalog.py
src/telliot_feeds/sources/price/spot/coingecko.py
src/telliot_feeds/sources/price/spot/uniswapV3.py

Adds SpotPrice feed for `CULT/USD` based on Dex Sources.
Local testing and reported to Sepolia:
`https://sepolia.etherscan.io/tx/0x1807cb506b96f7f72c28b49f21674b16e83ba0eefb8aae34a0a79f94d260d893`

cult-usd-spot
