- docs/contributing.md
- docs/getting-started.md
- setup.cfg
- Update installation docs
- Require telliot-core 0.0.5 to use rinkeby
> Rinkeby update

- scripts/report_usd_vwap.py
- src/telliot_feed_examples/cli.py
- src/telliot_feed_examples/reporters/interval.py
- src/telliot_feed_examples/reporters/report_legacy_price.py
- src/telliot_feed_examples/sources/ampl_usd_vwap.py
- src/telliot_feed_examples/sources/binance.py
- src/telliot_feed_examples/sources/bitfinex.py
- src/telliot_feed_examples/sources/bitflyer.py
- src/telliot_feed_examples/sources/bittrex.py
- src/telliot_feed_examples/sources/coinbase.py
- src/telliot_feed_examples/sources/coingecko.py
- src/telliot_feed_examples/sources/gemini.py
- src/telliot_feed_examples/sources/kraken.py
- src/telliot_feed_examples/sources/price_aggregator.py
- src/telliot_feed_examples/sources/uspce.py
- src/telliot_feed_examples/utils/log.py
- tests/utils/test_logging.py
Creates a default logger to use for `telliot-feed-examples`. It prints to stdout and logs to `~/telliot/telliot-feed-examples.log`.
Replaces print statements with logging.
Example usage:
```python
from telliot_feed_examples.utils.log import get_logger
logger = get_logger(__name__)
logger.info("sup")
```
> Add logging

- src/telliot_feed_examples/cli.py
- src/telliot_feed_examples/reporters/interval.py
Convert time based reward and query ID tips to eth.
Convert estimated profit to USD.
Add `--max-gas-price/-mgp` optional reporter command flag.
> convert rewards/profit, add max gas price flag

- src/telliot_feed_examples/reporters/interval.py
the depositStake() call to the oracle contract did not pass in the mandatory argument `num_retries`. it would fail on an unstaked address.
> added default number of retries to depositStake

- src/telliot_feed_examples/reporters/interval.py
- src/telliot_feed_examples/sources/ampl_usd_vwap.py
- src/telliot_feed_examples/sources/price_aggregator.py
- tests/conftest.py
- tests/reporters/test_interval_reporter.py
- tests/sources/test_ampl_usd_vwap_source.py
Adds handling in the `AMPLUSDVWAPSource` and `PriceAggregator`, so they return `(None, None`) when data sources return no new datapoints. This avoids the error in `statistics.median` that @Spuddyminer reported, because it won't try to find the median of an empty list (`prices`): 
```
= await asyncio.gather(
File "/telliot_feed_examples/sources/price_aggregator.py", line 87, in fetch_new_datapoint
result = self._algorithm(prices)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/statistics.py", line 430, in median
raise StatisticsError("no median for empty data")
statistics.StatisticsError: no median for empty data
```
Tests for no updated value retrieved.
> Add handling for no updated value retrieved from datafeed

- src/telliot_feed_examples/reporters/interval.py
Corrects profit calculation. Tip halving removed because this already happens in `tipQuery()` (solidity).
> Do not halve tips

- src/telliot_feed_examples/reporters/interval.py
- src/telliot_feed_examples/utils/log.py
- tests/utils/test_logging.py
added a filter and a filter handler to prevent the log from being flooded with repeat messages (annoying!)
the solution for now is to not send a log message if the last line of the log file contains the same message.
Closes #35
> prevent logging of reoccuring messages

- src/telliot_feed_examples/cli.py
- src/telliot_feed_examples/reporters/interval.py
- tests/reporters/test_interval_reporter.py
Closes #40 
Adds optional flag for setting the estimated gas price speed that's retrieved from [eth gas station API](https://docs.ethgasstation.info/gas-price).
Examples:
```
telliot-examples report -lid 59 --gas-price-speed fastest
```
```
telliot-examples report -lid 1 -gps safeLow
```
> Gas price speed flag

- src/telliot_feed_examples/feeds/btc_usd_feed.py
Also needed for compatibility with next telliot-core version, which removes CoinPrice
> Report to legacy query instead of deprecated CoinPrice

- src/telliot_feed_examples/cli.py
- src/telliot_feed_examples/reporters/interval.py
- tests/reporters/test_interval_reporter.py
Adds a flag to use a custom gas price (gwei) that overrides all other gas price settings: `--gas-price/-gp`.
Example:
```
telliot-examples -lid 1 report -gp 42
```
> Add gas price flag for CLI report command

- src/telliot_feed_examples/cli.py
- src/telliot_feed_examples/reporters/interval.py
- src/telliot_feed_examples/utils/contract.py
- tests/cli/test_cli.py
Adds custom gas flag option (`--gas/-g`).
Changes the rewards units of the log message to TRB.
Removes confusing log message about tips being burned.
Moves contracts helper function to utilities.
Gas flag option usage/example:
```
user:~$ telliot-examples -lid 1 report -g 350000 -p 2
Reporting legacy ID: 1
Current chain ID: 4
Lower bound for expected percent profit: 2.0%
Selected gas price speed: fast
Gas: 350000
...
```
Example updated rewards log message:
```
2021-12-07 05:45:45,240 - telliot_feed_examples.reporters.interval - INFO -
current tips: 5e-06 TRB
current tb_reward: 2.6066666666666665 TRB
gas: 350000
gas_price_gwei: 97
```
> Small changes from reporter users

- src/telliot_feed_examples/reporters/interval.py
- src/telliot_feed_examples/utils/oracle_write.py
Adds the custom gas limit from user to the oracle write. Before it wasn't updating the hard-coded 500000. Example transaction using gas limit of 350k: https://rinkeby.etherscan.io/tx/0xadc531336f11ce10561bde2bbd618d2d667e594fd2c37d37416e0ffd288b32f4
Needs this PR merged to pass: https://github.com/tellor-io/telliot-core/pull/168
> Pass gas limit param to submitValue oracle write

- docs/usage.md
- src/telliot_feed_examples/cli.py
- tests/cli/test_cli.py
Adds default value for legacy id flag option, so help command can be used intuitively:
```
telliot-examples report --help
```
This threw an error before this change because legacy id flag was required.
> Make help commands more user-friendly

- src/telliot_feed_examples/cli.py
- tests/cli/test_cli.py
Closes #76 by adding a default profit threshold of 100%, so the reporter most likely won't submit if ran with the default settings (ex: `telliot-examples report`). Doesn't use a default of 0% because slippage could still result in the user losing money.
Fixes some errors coming from `get_app()` in `cli.py`. It was breaking because by default those values are `None`, so the app's config values were being overwritten when they shouldn't.
Adds test for `get_app()`.
> Add default profit threshold, ensure flags passed before override

- src/telliot_feed_examples/cli.py
Was passing `get_default_staker()` to reporter
> Fix stager tag option bug

- src/telliot_feed_examples/cli.py
- tests/cli/test_cli.py
Adds command line flag option (`--query-tag/-qt`) for selecting reporter datafeed by query tag (human-readable string).
Example usage:
```
telliot-examples -st staker9000 report -qt ohm-eth-spot
```
See supported query tags [here](https://github.com/tellor-io/dataSpecs/blob/main/catalog.md).
Closes #81
> Add option to select data feed using query tag

- .github/workflows/py39.yml
- src/telliot_feed_examples/cli.py
- src/telliot_feed_examples/utils/diva_protocol.py
- tests/cli/test_cli.py
- tests/conftest.py
- tests/utils/test_diva.py
Closes #114 
Reporting data for Diva Protocol:
```
telliot-examples -a fakename report --pool-id 147
```
Closing the pool:
```
telliot-examples -a fake name settle -pid 147
```
> Support manual reporting for Diva Protocol on Polygon

- src/telliot_feed_examples/cli.py
- src/telliot_feed_examples/reporters/flashbot.py
- src/telliot_feed_examples/reporters/interval.py
- src/telliot_feed_examples/reporters/tellorflex.py
Unlocks signature `ChainedAccount` for use in the `FlashbotsReporter`.
Removes `--flashbots` flag option. Now, `FlashbotsReporter` is used if a signature account name is provided.
Example:
```telliot-examples -a eth1 -sa sig1 report```
Closes: [#225](https://github.com/tellor-io/telliot-core/issues/225) from `telliot-core`
> Fixes flashbots error

- src/telliot_feed_examples/feeds/gas_price_oracle_feed.py
- src/telliot_feed_examples/sources/gas_price_oracle.py
- tests/feeds/test_gas_price_oracle_feed.py
For the GasPriceOracle DataFeed and DataSource, I've removed the `api_key` as a requirement for querying the owlracle gas price API, as it has a keyless free tier.
> stripped API key + tested feed

- src/telliot_feed_examples/feeds/diva_protocol_feed.py
- tests/feeds/test_diva_feed.py
Tests were erroring out because the import statements needed to be update bc of `telliot-core` changes
> Fix DIVA query imports

- src/telliot_feed_examples/feeds/gas_price_oracle_feed.py
- src/telliot_feed_examples/sources/gas_price_oracle.py
- tests/feeds/test_gas_price_oracle_feed.py
Closes #187 
For compatibility the `IntervalReporter` interface, I removed the arguments for `GasPriceOracleSource.fetch_data_point()`, which used to be `chain_id` and 'timestamp`.
> Unskips tests, removes args from fetch_data_point()

- src/telliot_feed_examples/feeds/__init__.py
- src/telliot_feed_examples/feeds/gas_price_oracle_feed.py
- src/telliot_feed_examples/sources/gas_price_oracle.py
- src/telliot_feed_examples/sources/price/spot/gemini.py
- tests/sources/test_gas_price_oracle_source.py
- tests/sources/test_spot_price_sources.py
closes #182 
get requests with python `requests` library returns a message, even if the http request was unsuccessful. This update catches bad requests in the WebPriceService class. This will prevent telliot from crashing on an unsuccessful API request.
Tested on the GeminiPriceService to match #182
> catch bad requests in WebPriceService class

- tests/feeds/test_active_feeds.py
- tests/feeds/test_bct_usd_feed.py
- tests/feeds/test_idle_usd_feed.py
- tests/feeds/test_matic_usd_feed.py
- tests/feeds/test_mkr_usd_feed.py
- tests/feeds/test_ric_usd_feed.py
- tests/feeds/test_sushi_usd_feed.py
- tests/feeds/test_usdc_usd_feed.py
If tests start failing because of coingecko rate limits, then they should detect that by reading the output from the logs
> Unskip rate limited tests & active feeds

- src/telliot_feed_examples/cli.py
- src/telliot_feed_examples/feeds/tellor_rng_feed.py
- src/telliot_feed_examples/sources/blockhash_aggregator.py
- tests/sources/test_tellor_rng_source.py
- adds support for reporting TellorRNG values using telliot cli
- use commands: `--rng-timestamp`, `-rngts`, or `rng_timestamp` followed by the desired timestamp argument
> add tellorrng cli support

- src/telliot_feeds/cli/commands/report.py
Fixes this:
```
(tenv) ubuntu@ip-fake:~$ telliot-feeds -a rinkeby3 report -p 101 -wp 120
...
Current chain id (4) not supported for reporting Diva Protocol data.
Diva Protocol not supported for this chain
```
> Fix false positive diva reporting

- src/telliot_feeds/reporters/interval.py
- tests/reporters/test_interval_reporter.py
The last reporter's submission timestamp wasn't reset after attempts to submit values, so when the transaction reverted, it wouldn't reset the timestamp; thus, wouldn't check if it was in reporter lock.
This change ensures the timestamp is reset before any submit val attempt. See `tests/reporters/test_interval_reporter.py::test_ensure_reporter_lock_check_after_submitval_attempt` for the example.
Closes #260
> Fix reporter lock bug

- .github/workflows/release.yml
- src/telliot_feeds/__init__.py
- Fixes the API keys for test & official pypi.org
- Bumps package version
> Prepare for new release 0.1.0

- src/telliot_feeds/reporters/interval.py
- src/telliot_feeds/reporters/tellorflex.py
Minor fix: telliot was breaking because a method in interval.py was not given the "self" arg
https://github.com/tellor-io/telliot-feeds/blob/5ce625a0062f14b787923bf54b6a7c4bd4554c5d/src/telliot_feeds/reporters/interval.py#L295
Closes #356 
submitted txn using telliot: https://mumbai.polygonscan.com//tx/0x38cc45e8ea8b96bb92797c8277c1389b4749ae888a1e058ea6a91a8d96eb9eeb
- Please reference the related issue by …
> online method missing self arg

- src/telliot_feeds/reporters/reporter_autopay_utils.py
- tests/reporters/test_autopay_multicalls.py
Multicalls in this `reporter_autopay_utils` did not have error handling, so I added error handling for `ValueError`s for RPC errors and `web3.exceptions.ContractLogicError` for contract reversions.
I also added more specific type hints to the multicall functions.
- Ran pytest, removed expected raise of `ContractLogicError`
- Ran mypy to improve type hints
- Please reference the related issue by including "Closes …
> more specific type hints, value errors in Multicall

- src/telliot_feeds/reporters/reporter_autopay_utils.py
fixes in this issue #339 had breaking changes causing the tests/test_autopay.py test to fail similar to #364 and #365 so the code was amended and the test is passing.  Researched the original issue #339 and the reason for that is documented here [Arbitrum Dev Center](https://developer.offchainlabs.com/time).  Basically arbitrum block numbers are produced differently than ethereum and so the multicall contract call errored.  There is an arbitrum multicall contract on mainnet Arbitrum but couldn't find a testnet address so deployed and verified ([Link](https://testnet.arbiscan.io/address/0xb84C5c81A9774722701d751bd3D2c0f19bfC25fa#code)) the mainnet contract on testnet and added the address in telliot_feeds.
closes #364
closes #365
- ran both tests concerning reporter_autopay_utils.py and …
> fix failing test with similar error 364/365

- src/telliot_feeds/reporters/reporter_autopay_utils.py
- tests/reporters/test_autopay_multicalls.py
Autopay contract on Polygon mainnet was reverting when trying to call getIndexForDataBefore (I checked this manually) so multicall was returning None instead of 0 which is the response on Mumbai (not sure why the difference). So added a catch for such a response when trying to loop over a range of None instead of numbers.
Closes #378 
Added a test with a mock response to test the scenario after the fix and the test passes locally.
- Please make sure docs are …
> fix error 378

- src/telliot_feeds/feeds/__init__.py
- Added RNG source for auto value input to ```DATAFEED_BUILDER_MAPPING```.  Currently the source available in ```DATAFEED_BUILDER_MAPPING``` requires a manual value input which could be useful if the Apis are down for some reason.  The source already exists in telliot-feeds, so just added it to the mapping.
Submitted a transaction going through the process of reporting through the ```--build-flag```.  [Transaction Link](https://mumbai.polygonscan.com/tx/0xbdb0407494cafe3f22418909fccc1cf208cf4042c98e2dce52cce0c2c3880565)
- Please include tests. Fixes without tests will …
> Add RNG source for auto value input to ```DATAFEED_BUILDER_MAPPING```

- src/telliot_feeds/reporters/tellor_360.py
- tests/reporters/test_360reporter.py
- Staking the chosen amount at cli was broken by a previous change I made so fixed it.  Now you should be able to stake more based on the chosen amount at cli. Closes #409 
- Added a test thats passing locally as well as depositing more stake than required through the cli.  [Txn](https://mumbai.polygonscan.com//tx/0x6cfdc44c65841e822bc9484deb31ce6b90aaa1ff8d7ed04efed14332724cf1f8)
- Please reference the related issue by including Closes #409 in this Pull Request's summary section. 
- Please reference the related issue by …
> Fix ability to stake more

- src/telliot_feeds/cli/commands/report.py
- Removed a line on commands/report.py that was causing the transaction type selection to be overridden.
- Closes #422 
Submitted a transaction on mumbai where I couldn't find docs on if EIP-1559 was implemented. Although there is this forum [Link](https://forum.polygon.technology/t/eip1559-implementation-on-mumbai-testnet/399).
[Transaction Link Mumbai](https://mumbai.polygonscan.com/tx/0x098749961a11fb87f32f06c2250a51b0d033c52ca447db4eb9c748ab47da307d)
Mainnet-Eth, Görli, and Polygon-mainnet all have EIP-1559 implemented so there shouldn't be an issue with submitting type 2 transactions
- If no issue exists, please create …
> Fix bug causing txn type choice to be overridden

- src/telliot_feeds/reporters/rewards/time_based_rewards.py
- Fix time based rewards calculation
- Closes #425 
- Ran same test from previous to check if telliot would break on errors and it passed. 
- Submitted transaction on Görli to see if amount dispersed  was the same as telliot calculation. [Transaction Link](https://goerli.etherscan.io/tx/0x1ce66716a60ec7be8f3ad27e1487737b5e16ba68c754077010251be995458513).
Telliot output:
- Please reference the related issue by …
> Fix TBR calculation

- src/telliot_feeds/cli/commands/integrations.py
- src/telliot_feeds/cli/main.py
- src/telliot_feeds/integrations/diva_protocol/cli.py
- tests/cli/test_diva_cli.py
- Closes #435 
- Adds commands to view/clear local cache of reported/settled pools:
```console
$ telliot-feeds integrations diva cache --help
Usage: telliot-feeds integrations diva cache [OPTIONS] COMMAND [ARGS]...
Commands for interacting with reported/settled pools cache (pickle file).
Options:
--help  Show this message and exit.
Commands:
clear  Clear reported/settled pools cache.
view   View reported/settled pools cache.
```
- `update_reported_pools` function already tested, so just added tests for the newly available commands. And did some sanity checks on my machine to make sure cmds works.
- If no issue exists, please …
> Add integrations cmd, add DIVA clear/view cache cmd

- src/telliot_feeds/reporters/tips/listener/funded_feeds_filter.py
- src/telliot_feeds/reporters/tips/multicall_functions/multicall_autopay.py
- tests/tips/conftest.py
- tests/tips/test_feed_suggestion.py
- tests/tips/test_multicall_autopay.py
- tests/tips/test_tips_available_after_submission.py
- Fixed bug that was causing price threshold to always be met.
- Fixed a test that was failing in github actions (not sure why)
- Found another bug that wasn't taking into account current value feed balance calculation and made changes
- Added a new test that tests feed balance calculations taking into account previous eligible submissions and that checks that a feed shouldn't be suggested if feed balance has been exhausted.
- Added a new test that shows a one time tip query id is not suggested after a value submission.
- Closes #477
- Closes #459
- Ran tests/tips folder and ensured all tests were passing
- Added new test that covers code changes
- Please reference the related issue by including "Closes `<link to issue>`" in this Pull …
> Fix bug 477

- src/telliot_feeds/feeds/snapshot_feed.py
- src/telliot_feeds/sources/blockhash_aggregator.py
- src/telliot_feeds/sources/manual/snapshot.py
- tests/sources/test_tellor_rng_source.py
- Missed 2 sources (snapshot & rng) that needed implementation of input w/ timeout, closes #507 
- TeStEd lOcAlLy:
```console
$ /Users/owen/tellor/telliot-feeds/env/bin/python /Users
/owen/tellor/telliot-feeds/src/telliot_feeds/sources/blockhash_aggregator.py
Enter timestamp for generating a random number: 
12341234
Generating random number from timestamp: 12341234
Press [ENTER] to confirm.
WARNING | __main__ | Blockchain.info API returned no blocks
WARNING | __main__ | Unable to retrieve Bitcoin blockhash
datapoint: None None
```
- Please include tests. Fixes without …
> Use input w/ timeout for snapshot & rng manual sources

- src/telliot_feeds/reporters/tips/listener/tip_listener_filter.py
- src/telliot_feeds/sources/blockhash_aggregator.py
- tests/feeds/test_manual_snapshot_feed.py
- tests/reporters/test_rng_reporter.py
Closes #506 
This is happening because of someone tipping TellorRNG query in autopay with an invalid timestamp.
- added a function that checks the timestamp and prompts the reporter to manually input a valid timestamp that the apis can return a value for.
- Added test that mocks an invalid timestamp
- tipped autopay with an invalid timestamp -> [Txn](https://mumbai.polygonscan.com/tx/0x04c5b4d7b0f1698e8b0a314b2c2cd4d63a528adb7ceefbca822cef521c18e7d7)
- submitted transaction thru telliot that required a manually entry -> [Txn](https://mumbai.polygonscan.com/tx/0x0f999682c1a141deed18ddf7140c93eab9a91178bdf32d5464f04f41b50ed38b)
- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. …
> Added function to check if timestamp is valid

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/eth_btc_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- tests/feeds/test_eth_btc_feed.py
This pull request will add an ETH/BTC feed for Badger that takes the median value for eth/btc when pulled from 4 sources: CoinGecko, Binance, Coinbase, and Gemini.
- Please make sure docs updates are both …
> add ETH/BTC median feed

- src/telliot_feeds/reporters/tellor_360.py
- src/telliot_feeds/reporters/tellor_flex.py
- tests/queries/test_query_support.py
- tests/reporters/test_360_reporter.py
- Closes #584 
- Setting a query parameter's value to a type that's not encodable given the abi type will reproduce the error; however, I do not know why this happened given Spuddy's original command. When would the reporter have a datafeed with a query that has incorrect parameter values?
- Added tests to reproduce error & check if handled (see Files Changed tab)
- [report tx](https://goerli.etherscan.io/tx/0x5de859ca32feb5e5612ccbe4978c5a15af5c94516dc9e49dae231a73a76c6c2e) using command Spuddy used that produced the error originally (excluding the stake 10000 part)
- …
> Fix encoding error

- src/telliot_feeds/feeds/albt_usd_feed.py
This pull request will remove the bitfinex source from ALBT. Trading seems to be frozen on most exchanges, so the only good sources right now are coingecko and coinmarketcap.
> removed bitfinex from ALBT-USD

- src/telliot_feeds/cli/commands/report.py
- src/telliot_feeds/cli/utils.py
- src/telliot_feeds/integrations/diva_protocol/report.py
- src/telliot_feeds/reporters/custom_reporter.py
- src/telliot_feeds/reporters/flashbot.py
- src/telliot_feeds/reporters/interval.py
- src/telliot_feeds/reporters/rng_interval.py
- src/telliot_feeds/reporters/tellor_360.py
- src/telliot_feeds/reporters/tellor_flex.py
- src/telliot_feeds/reporters/tips/__init__.py
- src/telliot_feeds/utils/reporter_utils.py
- tests/reporters/test_flex_reporter.py
- tests/reporters/test_interval_reporter.py
Closes #602 
Closes [#362](https://github.com/tellor-io/telliot-core/issues/362)
Closes [#355](https://github.com/tellor-io/telliot-core/issues/355)
Closes [#367](https://github.com/tellor-io/telliot-core/issues/367)
1. in command/report.py:
- removed speed flag used for gas api endpoint responses.
- add gas multiplier to up the gas price returned by web3 (optional)
2. in reporters/interval.py:
- change fetch_gas_price function to fetch gas price from web3 api instead of other apis' and returns a float to maintain the decimals especially when the number is close to zero.  The returned number is increased by the multiplier (default increase by 1 percent)
- switched flow between ensure_profitability and gas calculations to instead build transaction function, get gas price, then call …
> Use web3 for gas calculations usage/price

- src/telliot_feeds/cli/commands/report.py
- src/telliot_feeds/feeds/tellor_rng_feed.py
- src/telliot_feeds/reporters/rng_interval.py
- tests/reporters/test_rng_reporter.py
- Closes #614
- Fix bug that was causing RNG reporter to report same value multiple times for different query ids when following a successful report followed by a timestamp that didn't have a current block hash even though the query id was different.
- I think it was a scoping issue, the function that returns a datafeed was using a global source variable.
- Added a test to show the effects before the fix
- Another test to show the effects after the fix
- Currently reporting to make sure the fix was sufficient
- Please include tests. Fixes without tests will not be …
> Fix bug in RNG causing same value to be reported

- src/telliot_feeds/sources/evm_call.py
- tests/sources/test_evm_call_source.py
Adds block number parameter to `EVMCallSource.fetch_new_datapoint()` and `EVMCallSource.get_response()`, defaulting to `block_number= "latest"`. Some improved typing for the `get_response()` method as well
Added test `test_evm_call_on_previous_block` to ensure that calling a contract method at a previous block returns a different value than the same contract call on the current block. This was tested on a very active variable in the Tellor oracle contract: the value of the ETH/USD spot price.
`pytest tests/sources/test_evm_call_source.py`
- Please include tests. Fixes …
> Evm call source with optional blocknumber input

- src/telliot_feeds/utils/reporter_utils.py
- tests/utils/test_reporter_utils.py
The function `telliot_feeds.utils.reporter_utils.is_online()` did not handle the `Timeout` type of `requests` exceptions, which is raised sometimes in the Cloudflare DNS request.
I added the `requests.exceptions.Timeout` exception to be caught by the try-catch clause of the `is_online` function.
Added a mocking test for both possible exceptions, ensuring the function returns false if it cannot connect to the internet in both cases. I also tested that the log contains a message that `telliot` cannot connect to the internet. It includes the type and message of the exception as well.
- If no issue exists, please create a bug …
> Catch TimeoutError in `is_online` reporter utility

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/cny_usd_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- tests/feeds/test_cny_usd_feed.py
Summary
This PR makes two improvements to Telliot:
- Fixes the eur/usd spot price feed that was removed from query_catalog.py.
- Adds spot price feed add for CNY/USD. 
Changes were made following the telliot-feeds docs for adding a spot price, but no local tests were done. I tested the feeds by reporting on goerli / mumbai. The APIs all responded correctly. 
Here is the test report for CNY/USD:
https://mumbai.polygonscan.com/tx/0x9560fa117d56f5bf42a7b52e7e8571ff2e6c06cd8fc262425dcfedce76e2b12b
Here's the test report for ETH/JPY:
https://goerli.etherscan.io/tx/0x4366fa669cba4e94130a31e63b100147b6e472e4aa91713d767f0f47253bf6be
> add cny-usd feed & fixed eth-jpy feed

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/brl_usd_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- tests/feeds/test_brl_usd_feed.py
This PR makes changes neccessary for adding a new spot price feed: BRL/USD
Tested by reporting on goerli testnet. Log confirmed that two sources were successfully queried and the values were accurate. https://goerli.etherscan.io/tx/0x5ecb0eafa4fa09cd1361e650a2b92b56a0332794f236b49c3c0533415159bab6
A local test file was added for pytest.
> added brl-usd feed

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/oeth_eth_feed.py
- src/telliot_feeds/feeds/ousd_usd_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- src/telliot_feeds/sources/price/spot/coingecko.py
- src/telliot_feeds/sources/price/spot/uniswapV3.py
This pull request adds OUSD/USD and OETH/ETH feeds in response to dataSpecs issues https://github.com/tellor-io/dataSpecs/issues/124 and https://github.com/tellor-io/dataSpecs/issues/123. I will continue to work on adding more / multiple sources for both of these feeds, but wanted to push the branch so that others can contribute. 
Both feeds have been tested via local installation submitting to testnet Tellor contracts. 
OUSD/USD spot: https://goerli.etherscan.io/tx/0x319eee38c748fe571561b5d482c2c49ca7fb2611b5e16061a2c5ea2044cd086f
OETH/ETH spot: https://mumbai.polygonscan.com//tx/0x97b1fdd43bfe289b780507c039b02a12b062ac2bf35ad045d5c219e63daa7240
See the linked dataSpecs issues for more possible sources. Thanks for reading!
> adding Origin feeds: OUSD/USD and OETH/ETH

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/sweth_usd_feed.py
- src/telliot_feeds/feeds/wld_usd_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- src/telliot_feeds/sources/price/spot/coingecko.py
- src/telliot_feeds/sources/price/spot/uniswapV3.py
- tests/conftest.py
- tests/feeds/test_sweth_usd_feed.py
- tests/feeds/test_wld_usd_feed.py
This pull request adds new feeds to telliot. Rinkeby and Ropsten checks were removed from conftest.py. 
The new feeds were tested with pytest locally, and submitted to sepolia testnet:
https://sepolia.etherscan.io/tx/0x488373ed824c5870bbd289c74a163e8e008147414d0e79bf515afcdd8a49aed2
https://sepolia.etherscan.io/tx/0x619b09b06c8cd31312350578f2a0704338095daba9c32db392410af58b5a69f2
We will need to revisit these feeds to add more robust sources if / when they are used for DeFI functions.
- Please include tests. Fixes without tests will not be accepted unless it's related …
> WLD/USD & SWETH/USD Spot Price feeds & Removed Dead Testnet From Tests

- src/telliot_feeds/cli/commands/report.py
- src/telliot_feeds/cli/utils.py
- src/telliot_feeds/utils/cfg.py
- Creates `-u` option for unsafe mode, which skips configuration prompts. Default is False, so the default will prompt you. This is a draft, so that can be changed based on further discussion.
- Closes #693 
- WIP
- Please include …
> Add unsafe option to skip confirmation prompts

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/cbeth_usd_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- src/telliot_feeds/sources/price/spot/coingecko.py
- src/telliot_feeds/sources/price/spot/uniswapV3.py
- tests/feeds/test_cbeth_usd_feed.py
This pull request adds cbETH/USD as the median of three sources: coinGecko, uniswapV3, and coinPaprika.
Changes were tested with pytest after running tox styles / typing. Also reported the feed on goerli: 
https://goerli.etherscan.io/tx/0x893ba6517e2ed401719e0be590c2f310f122f206934a59f3be1df5c72093ea91
> Add CBETH/USD feed

- src/telliot_feeds/sources/ampleforth/bitfinex.py
- src/telliot_feeds/utils/cfg.py
This pull request will add the oracle contract address as part of the config info that Telliot shows at startup. This helps reporters check that they're not accidentally staking on an old oracle contract.
> Message to show oracle contract for chainId on start

- src/telliot_feeds/cli/commands/request_withdraw_stake.py
- src/telliot_feeds/cli/commands/stake.py
- src/telliot_feeds/cli/commands/withdraw.py
- src/telliot_feeds/cli/utils.py
Using the following commands gave an error that the `--unsafe` flag was unexpected: 
```
telliot stake
telliot request-withdraw
telliot withdraw
```
Added the unsafe flag to the function definitions for each command. Result is that the commands work as expected, however adding `--unsafe -pwd PASSWORD` does not bypass confirmations for these staking commands.
In my opinion the `--unsafe` flag is really only needed for the report command, so this is an acceptable solution! Let me know what you think if different 🤙
> Small Staking Commands fix

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/brc20_ordi_usd_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- src/telliot_feeds/sources/custom_price_aggregator.py
- src/telliot_feeds/sources/price/spot/coingecko.py
Added a BRC20 spot price feed (ORDI/USD) encoded as Custom Price query type. (Tippers will need to be adjusted to include encoding for all 4 CustomPrice parameters)
Test submission on sepolia:
https://sepolia.etherscan.io/tx/0x3fc8ec2fcce2af82d933e22bdc444731239b24d007eae825941e2d97ef507d93
> Added Custom Price Aggregator & ORDI/USD Spot

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/wbtc_usd_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- src/telliot_feeds/sources/price/spot/coingecko.py
- src/telliot_feeds/sources/price/spot/kraken.py
- src/telliot_feeds/sources/price/spot/uniswapV3.py
- tests/feeds/test_wbtc_usd_feed.py
Adds feed / sources for WBTC/USD Spot
local tests passing and test report to sepolia: 
https://sepolia.etherscan.io/tx/0x163a3509c83c4d6f12c7cf05f620f93de53d6a4edf580fc67da768e2dfc85595
> wbtc-usd-spot added

- src/telliot_feeds/sources/gyd_source.py
balancer updated their graph away from hosted service, so the URL changed.
> new Balancer V2 subgraph url

- src/telliot_feeds/feeds/usdm_usd_feed.py
- src/telliot_feeds/sources/price/spot/curvefiprice.py
- src/telliot_feeds/sources/price/spot/uniswapV3Pool.py
- src/telliot_feeds/sources/wusdm_source.py
- tests/feeds/test_usdm_usd_feed.py
- tests/feeds/test_wusdm_usd_feed.py
Quick fix for the usdm/usd feed removing curve and uniswap removed for now. Curve api is returning an incorrect price, and liquidity was pulled from mainnet uniswap.
(will need to try to fix curve and find at least one other source later)
> remove broken usdm sources

- src/telliot_feeds/sources/gyd_source.py
Switched the gyd feed from the developer subgraph over to the decentralized "production" subgraph that requires a graph api key.
> switch to production subgraph

- src/telliot_feeds/sources/gyd_source.py
this catch is no good (the error is preventable in telliot code, it's not an api error)
> Revert "catch balancer UnboundLocalError"

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/pufeth_usd_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- src/telliot_feeds/sources/price/spot/coingecko.py
- src/telliot_feeds/sources/price/spot/curvefiprice.py
- src/telliot_feeds/sources/price/spot/uniswapV3.py
- tests/feeds/test_pufeth_usd_feed.py
Adds puffer eth (`pufeth-usd-spot`) feed that uses a median of prices sourced from coingecko, uniswap, curvefi, coinpaprika.
pytest test added for `pufeth-usd-spot` and reported on sepolia:
https://sepolia.etherscan.io//tx/0xbf096aa072868546fcd712193d18fa9414c9accc56b58a4cea4f124fd7f5cc6a
- new spot price feed
> pufeth-usd-spot

- src/telliot_feeds/sources/superoethb_source.py
Fixed the routes used for querying the `superOETHb/eth` ratio:
```
CONNECTORS = [
"0xDBFeFD2e8460a6Ee4955A68582F85708BAEA60A3",  # superOETHb
"0x7002458B1DF59EccB57387bC79fFc7C29E22e6f7",  # OGNb
"0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",  # USDCb
"0x4200000000000000000000000000000000000006",  # wETHb
]
```
> fixed routing for superOETHb/eth pair

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/lsk_usd_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- src/telliot_feeds/sources/price/spot/kraken.py
- src/telliot_feeds/sources/price/spot/uniswapV3.py
- tests/feeds/test_lsk_usd_feed.py
Adds feed LSK/USD for dataSpecs issue #162: https://github.com/tellor-io/dataSpecs/issues/162).
added pytest test for the new feed and reported on sepolia: https://sepolia.etherscan.io/tx/0xb6d242c0f511616add8bc2c3b07431fdebdf33eb96086b1ee71a1444a38f266f
> add lsk/usd feed

- src/telliot_feeds/feeds/__init__.py
- src/telliot_feeds/feeds/op_usd_feed.py
- src/telliot_feeds/feeds/solvbtc_usd_feed.py
- src/telliot_feeds/feeds/solvbtcbbn_usd_feed.py
- src/telliot_feeds/feeds/unibtc_usd_feed.py
- src/telliot_feeds/queries/price/spot_price.py
- src/telliot_feeds/queries/query_catalog.py
- src/telliot_feeds/sources/lfj_source.py
- src/telliot_feeds/sources/price/spot/coingecko.py
- src/telliot_feeds/sources/price/spot/curvefiprice.py
- src/telliot_feeds/sources/price/spot/pancakeswap.py
- src/telliot_feeds/sources/price/spot/uniV3Optimism.py
- src/telliot_feeds/sources/price/spot/uniswapV3.py
- src/telliot_feeds/sources/solvbtcbbn_source.py
- tests/feeds/test_op_usd_feed.py
- tests/feeds/test_solvbtc_usd_feed.py
- tests/feeds/test_solvbtcbbn_usd_feed.py
- tests/feeds/test_unibtc_usd_feed.py
Adds feeds for `unibtc-usd-spot`, `solvbtc-usd-spot`, and `solvbtcbbn-usd-spot`. 
Local test added for each (passing) and reported on bob sepolia:
unibtc-usd-spot
https://bob-sepolia.explorer.gobob.xyz/tx/0xc828ff3c54a637ef874e10ff9ba7a2e11836afb4513382be92fc5a31e7aa7609
solvbtc-usd-spot
https://bob-sepolia.explorer.gobob.xyz/tx/0x7a79b528b7a4e23c83225bdbac9d46fe77ab92949ca4c9a4e417a67ec13f3345
Solvbtcbbn
https://bob-sepolia.explorer.gobob.xyz/tx/0x3301b909a40194d11bd1bcf1f4bf5c5ed56c9756d36a58911e27a39549e6529a
> New bob feeds

- src/telliot_feeds/sources/price/spot/curvefi.py
- src/telliot_feeds/sources/price/spot/curvefiprice.py
Fix for curve finance api urls.
"curve.fi" is now "curve.finance"
> curve fi url change

- src/telliot_feeds/feeds/usdt_usd_feed.py
- src/telliot_feeds/sources/gyd_source.py
- tests/feeds/test_usdt_usd_feed.py
This is a quick fix for two price feeds are currently not functioning properly. 
- Some change from the Okx api is causing the USDT/USD feed to crash out. Tried a few other feeds with okx source, and they seem to work fine. Proposing this super quick fix where we just remove it. (we have other good sources) 
- The balancer subgraph is no longer returning data about the pool for USDT/GYD as expected, so I removed that part of that source. This is also a band-aid, but it's a safe one as the source was / is very robust. 
Tested reporting on amoy/sepolia. local tests passing.
> fixed bugs in usdt and gyd
